### ISSUE TITLE
transitive build_dependencies cannot be found

### ISSUE THREAD

**Issue by Freed-Wu** [nvim-neorocks/lux#881]
```sh
lx add -b A
```

if `A`'s build_dependencies is `B`, and `B`'s build_dependencies is `C`, Then `C`'s build_dependencies will be installed to
```
.lux/5.3/build_dependencies/5.3/build_dependencies/5.3/bin
```

It cannot be found, so `B` will be failed to install.

[test.zip](https://github.com/user-attachments/files/21326689/test.zip)

**Comment by mrcjkb** [comment]
Do you have a specific example I can use to reproduce this?

**Comment by Freed-Wu** [comment]
```sh
lx new lx-test-a
cd lx-test-a
lx add -b lx-test-b
```

```
Caused by:
    failed to build lx-test-b: command build failed: error executing command:
    C

    error: No such file or directory (os error 2)

Location:
    /dev/shm/lux/lux-cli/src/utils/project.rs:71:10
```

`lx-test-b/lux.toml`:

```toml
package = "lx-test-b"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = ""
maintainer = "Wu"
labels = [""]

[source]
url = "https://github.com/user-attachments/files/21326689/test.zip"
dir = "."

[deploy]
wrap_bin_scripts = false

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[build]
type = "command"
build_command = "C"

[build.install.bin]
B = "test"

[build_dependencies]
lx-test-c = "0.1.0-1"
```

`lx-test-c/lux.toml`:

```toml
package = "lx-test-c"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = ""
maintainer = "Wu"
labels = [""]

[source]
url = "https://github.com/user-attachments/files/21326689/test.zip"
dir = "."

[deploy]
wrap_bin_scripts = false

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[build]
type = "builtin"

[build.install.bin]
C = "test"
```

**Comment by mrcjkb** [comment]
Thanks. But wouldn't I have to upload these to luarocks? What I meant by "specific example" was: is there a package on luarocks you've encountered this with?

**Comment by mrcjkb** [comment]
By the way thanks for all the digging for bugs you've been doing lately 🙏. This is really helping the project mature.

**Comment by Freed-Wu** [comment]
> But wouldn't I have to upload these to luarocks?

I have upload them to luarocks.org.

> is there a package on luarocks you've encountered this with?

The specific example are too complicated and related to many unimportant packages. So I create `lx-test-{a,b,c}` as a minimal example to reproduce it.

> all the digging for bugs

You're welcome. I expect that lux can replace luarocks for rocks.nvim and other projects based lua.

**Comment by mrcjkb** [comment]
It turns out this is not only an issue with the directory tree structure; we also don't install transitive build dependencies.

**Comment by mrcjkb** [comment]
@Freed-Wu I've implemented a fix in #883.

The `lx-test-b` rockspec you uploaded to luarocks.org is missing the `build_dependencies` table, but I uploaded a `lx-test-d` rockspec and it seems to be working.

**Comment by Freed-Wu** [comment]
I think the problem is not fixed fully.

```sh
lx new lx-test-o
cd lx-test-o
lx add -b lx-test-a
```

```
Error: syncing build dependencies with the project lockfile failed.

Caused by:
   0: error installing LuaRocks build dependencies: command build failed: error executing command:
   0: C

      error: No such file or directory (os error 2)
   1: command build failed: error executing command:
   1: C

      error: No such file or directory (os error 2)
   2: error executing command:
   2: C

      error: No such file or directory (os error 2)
```

`lx-test-a/lux.toml`:

```toml
package = "lx-test-a"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = ""
maintainer = "Wu"
labels = [""]

[source]
url = "https://github.com/user-attachments/files/21326689/test.zip"
dir = "."

[deploy]
wrap_bin_scripts = false

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[build]
type = "command"
build_command = "B"

[build.install.bin]
A = "test"

[build_dependencies]
lx-test-b = "0.1.0-1"
```

**Comment by mrcjkb** [comment]
That's because the PR is still open.

**Comment by Freed-Wu** [comment]
I try #883.

- For lx-test-a -> lx-test-b -> lx-test-c, it can work.
- For lx-test-o -> lx-test-a -> lx-test-b -> lx-test-c, it cannot work.

**Comment by mrcjkb** [comment]
Okay, I was able to reproduce it. It was failing because we don't add the build dependencies to the build tree's lockfile until all packages have been installed.

Fixed it now.
Thanks for testing 🙏
